package ThreadNaming;

public class ThreadDemo {
    public static void main(String[] args) {

        System.out.println(Thread.currentThread().getName());
        //currentThread() grabs the current thread object. getName() is used to get the name then.

        MyThread t = new MyThread();
        System.out.println(t.getName());
        t.setName("MT");
        System.out.println(t.getName());
    }
}

/*
    > Every thread in Java has some name, it may be default name generated by JVM or customized name provided by programmer.
    > We can get & set name of a thread by using following two methods of Thread class:
        1. public final String getName()
        2. public final void setName(String name)
 */
